spring:
  application:
    name: maylin.jauregui
  data:
    mongodb:
      uri: mongodb+srv://maylinjauregui:oTDesoVuG2nx4AdJ@cluster0.5djyl.mongodb.net/22_maylin_jauregui?retryWrites=true&w=majority
      database: 22_maylin_jauregui
  webflux:
    base-path: /

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

logging:
  level:
    ap1.maylin.jauregui: DEBUG
    org.springframework.data.mongodb: DEBUG
